
project:
  type: website
  output-dir: docs

website:
  title: "RwandaMarket"
  navbar:
    logo: ""
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Business Plan"
        href: business-plan.qmd
      - text: "Operations"
        href: operations.qmd
      - text: "Optimization"
        href: optimization.qmd
      - text: "Trade Benefits"
        href: trade-benefits.qmd
      - text: "Growth & Impact"
        href: growth-and-impact.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <style>
        .toc-title {
          color: #FFF !important;
        }
        </style>
    