project:
  title: "RwandaMarket"
  type: website
  output-dir: docs
  resources:
  - shinylive-sw.js

website:
  title: "RwandaMarket"
  navbar:
    logo: ""
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Business Plan"
        href: business-plan.qmd
      - text: "Operations"
        href: operations.qmd
      - text: "Optimization"
        href: optimization.qmd
      - text: "Trade Benefits"
        href: trade-benefits.qmd
      - text: "Impact"
        href: our-impact.qmd
      - href: contact.qmd
        text: "Contact"
      - href: sample_shiny_page.qmd
        text: "sample shiny"

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <style>
        .toc-title {
          color: #FFF !important;
        }
        </style>
