# File: _quarto.yml

project:
  type: website
  output-dir: docs

website:
  title: "RwandaMarket"
  navbar:
    logo: "images/rwandamarket-logo.png"
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Business Plan"
        menu:
          - executive-summary.qmd
          - company-description.qmd
          - market-analysis.qmd
          - products-services.qmd
          - marketing-strategy.qmd
          - operations-plan.qmd
          - management-team.qmd
          - financial-plan.qmd
      - text: "Operations"
        menu:
          - b2c-offerings.qmd
          - b2b-solutions.qmd
          - trade-regulations.qmd
          - consular-services.qmd
      - text: "Optimization"
        menu:
          - optimization-documentation.qmd
          - supply-chain-optimization.qmd
          - customer-experience-optimization.qmd
          - business-operations-optimization.qmd
      - text: "Trade Benefits"
        menu:
          - free-trade-benefits.qmd
          - product-origin-declaration.qmd
          - tariff-savings-tracking.qmd
          - non-tariff-barrier-reporting.qmd
      - text: "Growth & Impact"
        menu:
          - future-growth.qmd
          - our-impact.qmd
      - text: "Documentation"
        menu:
          - documentation-requirements.qmd
          - rapid-rollout.qmd
      - contact.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Quick Links"
        contents:
          - text: "Product Catalog"
            href: b2c-offerings.qmd
          - text: "B2B Services"
            href: b2b-solutions.qmd
          - text: "Trade Regulations"
            href: trade-regulations.qmd
          - text: "Contact Us"
            href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
